name: Publish CI

on:
  push:
    branches: [ main ]

jobs:
  build_publish:
    name: Sync to prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cp -r websites build

      - name: Deploy to prod branch
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: prod
          build_dir: build
          commit_message: Deploy to prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
